In [12]:
from sklearn import datasets

data = datasets.load_iris()

import pandas as pd

# Создадим DataFrame.
df = pd.DataFrame(data.data, columns=data.feature_names)
# Добавим столбец "target" и заполним его данными.
df['target'] = data.target
# Выведем на экран первые пять строк.
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

data = pd.DataFrame({'Region': ['A', 'B', 'C', 'A']})
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data[['Region']]).toarray()

In [15]:
print(data)

  Region
0      A
1      B
2      C
3      A


In [14]:
print(encoded_data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [17]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# Создадим DataFrame с данными
data = pd.DataFrame({
    'Household': ['Household 1', 'Household 2', 'Household 3', 'Household 4'],
    'Income': [50000, np.nan, 45000, 48000],  # Доходы с пропущенными значениями
    'Expenditure': [20000, 15000, np.nan, 18000]  # Расходы с пропущенными значениями
})

print("Исходные данные:")
print(data)

# Инициализируем SimpleImputer для замены пропущенных значений средним
imputer = SimpleImputer(strategy='mean')

# Преобразуем данные, заменяя пропущенные значения в столбце 'Income'
data['Income'] = imputer.fit_transform(data[['Income']])

# Преобразуем данные, заменяя пропущенные значения в столбце 'Expenditure'
data['Expenditure'] = imputer.fit_transform(data[['Expenditure']])

print("\nДанные после заполнения пропусков средним:")
print(data)


Исходные данные:
     Household   Income  Expenditure
0  Household 1  50000.0      20000.0
1  Household 2      NaN      15000.0
2  Household 3  45000.0          NaN
3  Household 4  48000.0      18000.0

Данные после заполнения пропусков средним:
     Household        Income   Expenditure
0  Household 1  50000.000000  20000.000000
1  Household 2  47666.666667  15000.000000
2  Household 3  45000.000000  17666.666667
3  Household 4  48000.000000  18000.000000


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Создаем DataFrame с данными
data = pd.DataFrame({
    'Age': [25, 30, 45, 35, 50, 40, 23, 37, 48, 55],
    'EducationLevel': [12, 16, 18, 14, 20, 16, 12, 15, 19, 21],
    'Income': [40000, 50000, 80000, 60000, 100000, 75000, 35000, 65000, 90000, 110000]
})

# Определяем признаки (X) и целевую переменную (y)
X = data[['Age', 'EducationLevel']]
y = data['Income']

# Разделяем данные на тренировочную и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train, y_train, cv=5)
print("Средняя точность: ", scores.mean())

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
from sklearn.preprocessing import Normalizer

normalizer = Normalizer(norm='max')
X_normalized = normalizer.fit_transform(X)

In [ ]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

data = load_boston()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [ ]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

data = load_boston()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [ ]:
from sklearn.linear_model import Ridge, Lasso

ridge = Ridge(alpha=1.0)
lasso = Lasso(alpha=0.1)

ridge.fit(X_train, y_train)
lasso.fit(X_train, y_train)